### PR TITLE
Front end design

### PR DESCRIPTION
**Pull request by athiemohamed**
Just implemented the homepage, need u'r help with courses page

### CODE REVIEW

**Comment by rand0mdev** [comment]
**This is a design a got when I go to the branch, I don't know if you pushed the latest changes ?**

Screen Shot 2020-03-28 at 1 47 03 AM
<hr>

### And i had no sql error

**Comment by rand0mdev** [comment]
> **This is a design a got when I go to the branch, I don't know if you pushed the latest changes ?**
> 
> Screen Shot 2020-03-28 at 1 47 03 AM
> 
> ### And i had no sql error

Now I see the changes, it was a problem with web browser catch.

**Comment by athiemohamed** [comment]
I was excepting that, here was some conflicts in the app.css let me fix it and push it again

**Comment by rand0mdev** [comment]
You can skip theses checks, for new want just lunch the first version

**Comment by rand0mdev** [comment]
You can remove the .history folder from git, it's too large 🙂

**Comment by athiemohamed** [comment]
Okay i just removed it, it was generated by VSCode i thin

**Comment by athiemohamed** [comment]
New PR and we're ready to merge with master branch

**Pull request merged**
